version: "3.7"
services:
  vlmcsd:
    build: .
    ports:
      - "1688:1688"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - vlmcsd
    restart: always
