version: "3.7"
services:
  vlmcsd:
    build: .
    ports:
      - "1688:1688"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/user/vlmcsd-docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vlmcsd
    restart: always
